var WEAPON_LETHALITY_DATA = [
  { "weapon": "BLUE_WEAPON_1", "platform": "blue_ship_1", "quantity": 12 },
  { "weapon": "BLUE_WEAPON_2", "platform": "blue_ship_1", "quantity": 8 },
  { "weapon": "BLUE_WEAPON_3", "platform": "blue_ship_2", "quantity": 6 },
  { "weapon": "BLUE_WEAPON_4", "platform": "blue_ship_2", "quantity": 10 },
  { "weapon": "BLUE_WEAPON_5", "platform": "blue_ship_3", "quantity": 4 },
  { "weapon": "BLUE_WEAPON_1", "platform": "blue_ship_4", "quantity": 14 },
  { "weapon": "BLUE_WEAPON_2", "platform": "blue_ship_5", "quantity": 7 },
  { "weapon": "BLUE_WEAPON_3", "platform": "blue_ship_6", "quantity": 5 },
  { "weapon": "BLUE_WEAPON_4", "platform": "blue_ship_7", "quantity": 9 },
  { "weapon": "BLUE_WEAPON_5", "platform": "blue_ship_8", "quantity": 3 },
  { "weapon": "RED_WEAPON_1", "platform": "red_ship_1", "quantity": 11 },
  { "weapon": "RED_WEAPON_2", "platform": "red_ship_1", "quantity": 6 },
  { "weapon": "RED_WEAPON_3", "platform": "red_ship_2", "quantity": 8 },
  { "weapon": "RED_WEAPON_4", "platform": "red_ship_2", "quantity": 13 },
  { "weapon": "RED_WEAPON_5", "platform": "red_ship_3", "quantity": 5 },
  { "weapon": "RED_WEAPON_6", "platform": "red_ship_4", "quantity": 9 },
  { "weapon": "RED_WEAPON_7", "platform": "red_ship_5", "quantity": 4 },
  { "weapon": "RED_WEAPON_8", "platform": "red_ship_6", "quantity": 7 },
  { "weapon": "RED_WEAPON_3", "platform": "red_ship_7", "quantity": 12 },
  { "weapon": "RED_WEAPON_4", "platform": "red_ship_8", "quantity": 10 }
];
